# This is a basic workflow to help you get started with Actions

name: Build Version

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

env:
  MONGODB_URL: ${{ vars.MONGODB_URL }}
  MONGODB_DATABASE: ${{ vars.MONGODB_DATABASE }}
  REDIS_ADDR: ${{ vars.REDIS_ADDR }}
  REDIS_PASSWORD: ${{ vars.REDIS_PASSWORD }}
  JWT_SECRET: ${{ vars.JWT_SECRET }}
  JWT_ISSUER: ${{ vars.JWT_ISSUER }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - uses: go-semantic-release/action@v1
        with:
          hooks: goreleaser
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}