# This is a basic workflow to help you get started with Actions
name: Release Version

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
    - main
    - alpha
  pull_request:
    branches:
    - main
    - alpha

env:
  MONGODB_URL: ${{ vars.MONGODB_URL }}
  MONGODB_DATABASE: ${{ vars.MONGODB_DATABASE }}
  REDIS_ADDR: ${{ vars.REDIS_ADDR }}
  REDIS_PASSWORD: ${{ vars.REDIS_PASSWORD }}
  JWT_SECRET: ${{ vars.JWT_SECRET }}
  JWT_ISSUER: ${{ vars.JWT_ISSUER }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  release:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    environment:
      name: "test"
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check Pre-release
        uses: haya14busa/action-cond@v1
        id: condval
        with:
          cond: ${{ github.ref == 'refs/heads/alpha' }}
          if_true: true
          if_false: false

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Semantic Version
        uses: go-semantic-release/action@v1
        with:
          hooks: goreleaser
          prerelease: ${{ steps.condval.outputs.value }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}